name: VKBinding
main: GreenMine\VKBinding\Main
version: 1.4.88
api: 3.8.4
load: STARTUP
author: GreenMine
description: Binding VK account
website: https://github.com/GreenMine

commands:
 acceptbind:
  description: "Привязать аккаунт"

 refusebind:
  description: "Отклонить привязку аккаунта"

 vkinfo:
  description: "Информация о привязанном аккаунте"